### ISSUE TITLE
Trying to create spark gives errors

### ISSUE THREAD

**Issue by ittayd** [alexarchambault/ammonium#30]
@transient val Spark =  new ammonite.spark.Spark
java.lang.reflect.InvocationTargetException
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:497)
    ammonite.interpreter.Interpreter$$anonfun$process$1$$anonfun$apply$21$$anonfun$apply$24$$anonfun$apply$25$$anonfun$11.apply(Interpreter.scala:259)
java.lang.NoSuchMethodError: ammonite.api.Classes.onPathsAdded(Lscala/Function1;)V
    ammonite.spark.Spark.<init>(Spark.scala:163)
    cmd1$$user$$anonfun$1.apply(Main.scala:50)
    cmd1$$user$$anonfun$1.apply(Main.scala:49)
    cmd1$$user.<init>(Main.scala:51)
    cmd1.<init>(Main.scala:55)
    cmd1$.<init>(Main.scala:30)
    cmd1$.<clinit>(Main.scala)
    cmd1$Main$.$main(Main.scala:25)
    cmd1$Main.$main(Main.scala)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:497)
    ammonite.interpreter.Interpreter$$anonfun$process$1$$anonfun$apply$21$$anonfun$apply$24$$anonfun$apply$25$$anonfun$11.apply(Interpreter.scala:259)

**Comment by ittayd** [comment]
load.ivy("com.github.alexarchambault" % "ammonite-spark_1.5_2.10.6" % "0.4.0-SNAPSHOT")

**Comment by alexarchambault** [comment]
Aren't you using incompatible versions of this (like `0.3.1-SNAPSHOT` for the shell, and `0.4.0-SNAPSHOT` for the ammonite-spark lib) ?

Maybe try with

``` scala
load.ivy("com.github.alexarchambault" % "ammonite-spark_1.5_2.10.5" % "0.3.1-SNAPSHOT")
```

(I'm using it successfully quite often.)

**Comment by ittayd** [comment]
Yes, this worked. But then how am I supposed to know what underlying Ammonite the Jupyter kernel is using vs what is available from ammonite-spark?

**Comment by neocsr** [comment]
I got the same error _java.lang.NoSuchMethodError: ammonite.api.Classes.onPathsAdded_.
I'm running `jupyter-scala_2.11.6-0.2.0-SNAPSHOT` with `ammonite-spark_1.5_2.11.6;0.4.0-SNAPSHOT`. 
Which would be the right version for ammonite-spark?

Thanks!

**Comment by alexarchambault** [comment]
@neocsr You should use jupyter-scala 0.3 (https://github.com/alexarchambault/jupyter-scala/tree/topic/update-readme), and follow [this example notebook](https://gist.github.com/alexarchambault/efa9e184c53fb2af6229). I'd like give some love to ammonium / jupyter-scala once [coursier](https://github.com/alexarchambault/coursier) 1.0 final is out.

**Comment by neocsr** [comment]
Awesome! Thanks!

**Comment by alexarchambault** [comment]
See [ammonite-spark](https://github.com/alexarchambault/ammonite-spark) now.
