### ISSUE TITLE
Can't start Spark

### ISSUE THREAD

**Issue by ittayd** [alexarchambault/ammonium#32]
In Jupyter:
Spark.withConf(_
  .setMaster("local[*]")
)
import Spark.sc
Spark.start()
:: problems summary ::
:::: ERRORS
    unknown resolver redefined-public

```
unknown resolver null

unknown resolver redefined-public

unknown resolver null
```

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/10/21 12:15:56 INFO Spark$SparkContext: Running Spark version 1.5.0
15/10/21 12:15:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/10/21 12:15:57 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
    at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:318)
    at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:333)
    at org.apache.hadoop.util.Shell.<clinit>(Shell.java:326)

Using Spark directly, it loads fine (but then there are issues with serialization). For example, the below code gets me a working context:
load.ivy("org.apache.spark" %% "spark-assembly" % "1.1.1")
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.rdd.RDD
@transient val sc = new SparkContext("local[*]", "Intro")

**Comment by alexarchambault** [comment]
See [ammonite-spark](https://github.com/alexarchambault/ammonite-spark) now.
