### ISSUE TITLE
Ammonite REPL context is not imported

### ISSUE THREAD

**Issue by Aivean** [alexarchambault/ammonium#41]
Seems that [`readme`](https://github.com/alexarchambault/ammonium/blob/master/README.md) is outdated, I could not find `shell/target/pack/bin/ammonite` to run after build.

Instead I tried to run (from project directory) `./launch` , `./ammonium` and `./shell/core/target/pack/bin/ammonite`.
They started ammonite repl, but ammonite's ["builtins"](http://lihaoyi.github.io/Ammonite/#Builtins) were not available (I mean things such as `load`, `help`).

```
@ load
Main.scala:24: not found: value load
load
^
@
```

Can you please look into it? Most probably I'm missing something obvious.

**Comment by alexarchambault** [comment]
@Aivean I pushed a draft of an updated README (https://github.com/alexarchambault/ammonium/pull/42), it can be seen from https://github.com/alexarchambault/ammonium/tree/topic/update-readme. (It should be finished and pushed to master in a few days...)

**Comment by Aivean** [comment]
Thanks a lot! This solves my issue!
