### ISSUE TITLE
Cannot specify classpath entries filtered out of Spark conf

### ISSUE THREAD

**Issue by mallman** [alexarchambault/ammonium#52]
Ammonium's `ammonite.spark.Spark` class adds all jars on the classpath to Spark's configuration except some hard-coded dependencies: https://github.com/alexarchambault/ammonium/blob/43400ac2bb4712eaeb64dc7db886624fb595db8f/spark/src/main/scala/ammonite/spark/Spark.scala#L110-L113.

I'd like to be able to filter out other jar files that are already on the executors' classpaths.

To me, the most natural approach is to add a "provided" classpath configuration that works like the Ivy/sbt configuration of the same name. Then filter out any dependency on the "provided" classpath.

Another approach would be to open an API in the `Spark` class for callers to manually specify jars/modules to omit from the Spark configuration.

**Comment by alexarchambault** [comment]
Re-open this issue in [ammonite-spark](https://github.com/alexarchambault/ammonite-spark) if it's still a problem for you. It can be used from the latest Ammonite, and should also be easier to tweak.
