### ISSUE TITLE
Adding credentials for private maven repository

### ISSUE THREAD

**Issue by shaulzorea** [alexarchambault/ammonium#66]
Hi there,

I have a private maven repository protected by a password from which I'd like to import dependencies.
`classpath` has a `addRepository` method however I don't see a way to specify its credentials.
Is that possible? If not, is there a workaround

Much thanks,
Shaul.

**Comment by wpc009** [comment]
Does this feature get supported?

**Comment by shaulzorea** [comment]
No to the best of my knowledge.

I needed it for working on a scala notebook over Jupyter - you could modify your credentials instead:
i.e
in: ~/.ivy2/.credentials

realm=Nexus
host=your.domain.com:9000
user=johndoe
password=XXXXXXX

I hope this helps.
