### ISSUE TITLE
Merge Ammonite 0.8.3 from upstream

### ISSUE THREAD

**Issue by mallman** [alexarchambault/ammonium#79]
From a purely personal perspective, Ammonite 0.8.3 includes a commit (that I contributed), https://github.com/lihaoyi/Ammonite/commit/08728680827083e0d7b1323ba3f544419fa45f7d, that greatly improves the performance of dynamically loading a large number of jar files. Incorporating this feature into ammonium and jupyter-scala would be a huge improvement in the usability of the jupyter-scala kernel for us. Thank you.

**Comment by alexarchambault** [comment]
I'll merge with upstream and do a new release before the end of the week I think. I'd like to have it use coursier `1.0.0-RC2` too (to be released).

**Comment by alexarchambault** [comment]
@mallman Your commit is already included in ammonium (since `0.8.2`): https://github.com/alexarchambault/ammonium/commit/08728680827083e0d7b1323ba3f544419fa45f7d. So in jupyter-scala `0.4.0` too.

**Comment by mallman** [comment]
Oh that's cool. And unexpected for me, because it's not in Ammonite 0.8.2. Glad to see it got ported over though. Thanks!

**Comment by alexarchambault** [comment]
[ammonite-spark](https://github.com/alexarchambault/ammonite-spark) is now live, and allows to do spark stuff from the latest Ammonite.

**Comment by mallman** [comment]
> ammonite-spark is now live, and allows to do spark stuff from the latest Ammonite.

Hi @alexarchambault. Many thanks for your work on this. VideoAmp makes heavy use of your Scala kernel for Jupyter, including to connect to Spark. I'm glad to see ammonite-spark go live. What isn't clear is how to integrate it with Jupyter. Is that possible at this point? Is that a WIP?

Thanks.

**Comment by alexarchambault** [comment]
It's not published yet, but it works fine. I should release the next iteration of jupyter-scala, with that, in the coming days if all goes well (working on it at my current company).
